name: habits-manager

services:
  postgres:
    image: docker.io/postgres:16.8-alpine3.20
    container_name: habits-manager-db
    env_file: .env
    environment:
      POSTGRES_DB: habits_manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
    ports:
      - "5432:5432"
    networks:
      - habits-manager-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "psql -d habits_manager -U admin -c 'SELECT 1' || exit 1"
      interval: 3s
      timeout: 1s
      retries: 2
      start_period: 2s

  habits-manager-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: habits-manager-api:latest
    container_name: habits-manager-api
    env_file: .env
    environment:
      JDK_JAVA_OPTIONS: -Xms256m -Xmx512m -Dspring.profiles.active=test
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: habits_manager
      DATABASE_USER: admin
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-admin}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - habits-manager-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:

networks:
  habits-manager-network:
    driver: bridge
