spring.application.name=habits-manager
spring.profiles.active=dev
spring.jpa.open-in-view=true
api.security.token.secret=${SECRET_KEY:secret}
spring.ai.openai.api-key=${LLM_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=${LLM_CHAT_MODEL:llama-3.3-70b-versatile}
spring.ai.openai.chat.options.temperature=${LLM_CHAT_TEMPERATURE:0.7}